### ISSUE TITLE
Sovryn node base improvements

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/Sovryn-Node#6]
- [ ] Automated swap back after liquidation DistributedCollective/Sovryn-Watcher#10
- [ ] Frontend with more live stats DistributedCollective/Sovryn-Node#4 
- [ ] DB export with transaction history DistributedCollective/Sovryn-Node#3 
- [ ] finish all open todos in comments DistributedCollective/Sovryn-Watcher#15 
- [ ] Bugfixes (stats) DistributedCollective/Sovryn-Node#2 
- [ ] Add infos to telegram notifications (pos-size, coin) DistributedCollective/Sovryn-Node#5

**Comment by jamiemadrox779** [comment]
sounds good
